server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: team-manager-service
          uri: lb://pokemon-team-manager-service
          predicates:
            - Path=/team_manager/**
        - id: catalogue-service
          uri: lb://pokemon-catalogue-service
          predicates:
            - Path=/catalogue/**
        - id: trainer-service
          uri: lb://pokemon-trainer-service
          predicates:
              - Path=/trainer/**
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/security/**

